### ISSUE TITLE
backwards binary compatibility of libmuser

### ISSUE THREAD

**Issue by tmakatos** [nutanix/muser#64]
In libmuser we export some critical structs, e.g. `lm_dev_info`, `lm_cap_t`. Doing so makes coding for the user simpler, however we risk not being able to upgrade libmuser while maintaining backward compatibility, since we won't be able to modify these structs without breaking it. Therefore it would be better to make these structs opaque and introduce public functions for e.g. initializing `lm_dev_info`. @swapnili @franciozzy thoughts?

If we still want to keep some structs public, we might have to do something similar to VFIO: introduce an `argsz` member at the beginning of the struct so that we know the amount of data passed by the user and only append new struct members whenever we have to change them.

**Comment by tmakatos** [comment]
We should make most libmuser structs private and use functions instead.

**Comment by jlevon** [comment]
For an example, let's take lm_cap_t. Currently, if we need to add a cap that changes the ABI size of lm_cap_t, that breaks ABI compatibility completely for all existing clients, because we have an array of lm_cap_t incoming in lm_dev_info_t.

But instead we could have something like:

lm_ctx_add_pci_cap(lm_ctx_t *ctx, uint8_t cap_id, char *cap_buf, size_t cap_size);

If we want to support a new capability, then, we don't need to make incompatible changes to the API and ABI (though of course older libmuser versions won't support the new cap).

I think Thanos is suggesting we review the entire API for this sort of issue, and in general avoid exporting any public struct. Probably the first step here is to go through the API in detail and see what potential issues we can identify here.

**Comment by tmakatos** [comment]
> I think Thanos is suggesting we review the entire API for this sort of issue, and in general avoid exporting any public struct. Probably the first step here is to go through the API in detail and see what potential issues we can identify here.

Exactly!

**Comment by tmakatos** [comment]
fixed by #115
